app/main/routes.py
from flask import (
    Blueprint,
    render_template,
    session,
    request,
    redirect,
    flash,
    abort,
    url_for
)
from app import db
from app.models import *
from app.users.utils import *

main = Blueprint('main', __name__)


@main.app_template_filter('get_img')
def get_img(img):
    return storage.child(img).get_url(firebase_user["idToken"]) if img \
        != "default.jpg" else url_for('static', filename='images/default.jpg')


@main.route("/post_answer/<string:ques_id>", methods=["POST"])
def post_answer(ques_id):
    print(ques_id)
    ansBody = request.form.get("answer")
    ques = Question.query.filter_by(sno=ques_id).first()

    answer = Answers(answer=ansBody,
                     username=session["user"],
                     date=datetime.strftime(datetime.now(), "%d-%m-%y"),
                     owner=ques,
                     answer_user=Detail.query.filter_by(username=session["user"]).first())
    db.session.add(answer)
    db.session.commit()
    flash("Answer Posted Successfully")
    return redirect(
                url_for("main.ques_page",
                        sno=answer.ques_id,
                        slug='-'.join(answer.owner.title[0:40].split(' '))) +
                f"#a{answer.ans_no}")


@main.route("/edit_answer/<string:sno>", methods=["POST", "GET"])
def edit_answer(sno):
    ans = Answers.query.filter_by(ans_no=sno).first()
    ansBody = request.form.get("answer")
    if request.method == "POST":
        if session["user"] == request.form.get("username"):  # editing answer
            answer = Answers.query.filter_by(ans_no=sno).first()
            answer.answer = ansBody
            db.session.commit()
            flash("Answer edited successfully", "success")
        else:
            flash("Error could not post your answer", "danger")
        return redirect(
                url_for("main.ques_page",
                        sno=answer.ques_id,
                        slug='-'.join(answer.owner.title[0:40].split(' '))) +
                f"#a{answer.ans_no}")
    return render_template("edit_answer.html",
                           answer=ans,
                           sno=sno,
                           username=session["user"])


@main.route("/cast_vote", methods=["POST"])
def cast_vote():
    if "user" in session:
        Voteuser = request.form.get("voteuser")  
            
        if Voteuser == session["user"]:  # if user voted his own ans or ques .
            return "sameuser"
        aq = request.form.get("type")  # if question vote or answer vote
        votetype = request.form.get("votetype")  # if downvote , upvote or novote
        ques_no = request.form.get("ques_no")  # sno of voted ans or ques
        user_vote = Vote.query.filter_by(username=session["user"],
                                        no=ques_no,
                                        aq_vote=aq).first()
        
        
        if aq == "answer":
            my_ans = Answers.query.filter_by(ans_no=ques_no).first()  # if answer voted update it to vote column in db
            print(my_ans)
            if user_vote:
                if user_vote.votetype == "downvote":
                    my_ans.votes -= 1 if votetype == "novote" else 2
                    print(my_ans.votes, "down")
                else:
                    my_ans.votes += 1 if votetype == "novote" else 2
                    print(my_ans.votes, "up")
            else:
                if votetype == "upvote":
                    my_ans.votes += 1
                else:
                    my_ans.votes -= 1
        else:
            pass
        if votetype != "novote":  # if downvote,upvote add it to db
            if not user_vote:  # if vote don't exist then make a new row
                voted = Vote(username=session["user"],
                            no=ques_no,
                            votetype=votetype,
                            aq_vote=aq,
                            Vote_user=Detail.query.filter_by(username=session["user"]).first(),
                            vote_owner=Answers.query.get(ques_no))

                db.session.add(voted)
            else:
                user_vote.votetype = votetype  # else update the earlier one
        else:
            db.session.delete(user_vote)  # if novote then delete the row
        db.session.commit()
        return {"user": session["user"]}
    return "login"

@main.route("/<string:sno>/<string:slug>", methods=["GET", "POST"])  # sno=question no,slug=ques_title 
def ques_page(sno, slug):

    ques = Question.query.filter_by(sno=sno).first()  # taking question on based on sno
    if not ques:
        abort(404)
    answers = Answers.query.filter_by(ques_id=sno).order_by(  # answers of the question
        Answers.real_answer.desc(), Answers.date.desc()).all()  # in desednign order.
    a = []
    # for adding comments to a ques or ans 
    for ans in answers:
        comments = Comments.query.filter_by(sno=ans.ans_no).all()  # comment for ans
        a.append(comments)
    comment = Comments.query.filter_by(ques_sno=sno).all()  # comment for question

    if "user" in session and session["loggedin"] is True:
        # allow user to answer,comment,edit,delete if loggedin
        # votes to answer and question
        ques_vote = Vote.query.filter_by(username=session["user"],
                                         no=sno,
                                         aq_vote="ques").first()
        ans_vote = Vote.query.filter_by(username=session["user"],
                                        aq_vote="answer").all()    
        # some get request vars
        real = request.args.get("real_answer")  # if marked as accepted or correct
        tab = request.args.get("tab")
        # for marking accepted answer
        if real is not None:
            print(request.args.get("number"),"hi")
            my_answer = Answers.query.filter_by(
                ans_no=request.args.get("number")).first()
            before_request = my_answer.real_answer
            if my_answer.username == session["user"]:
                my_answer.real_answer = real
                db.session.commit()
                if len(Answers.query.filter_by(real_answer="true").all()) <= 1:
                    return "success"  # adding the true or false and returning success,
                my_answer.real_answer = before_request
                db.session.commit()
            return "If you do this again. You will be banned from site."\
                + session["user"]

        if tab == "oldest":
            answers = Answers.query.filter_by(ques_id=sno).order_by(
                Answers.real_answer.desc(), Answers.date).all()  # sorting by first real_answer so if it is oldest 
            
            return render_template(
                "main.html",
                ques="ques",
                question=ques,
                answers=answers,
                username=session["user"],
                slug=slug,
                comments=a,
                comment=comment,
                ans_vote=ans_vote,
                ques_vote=ques_vote)
    # authentication
    elif "user" not in session:
        if request.method == "POST":  # if user is not login and try to answer or ... then send to signin page
            flash("Login To continue", "warning")
            return redirect("/signin")
        elif request.args.get("real_answer"):  # if voting without login then also
            flash("Login To mark", "warning")
            return "login"

    return render_template("main.html",
                           question=ques,
                           answers=answers,
                           slug=slug,
                           comments=a,
                           comment=comment)

app/question/routes.py
from flask import Blueprint,render_template,session,request,redirect,flash,url_for
from flask_sqlalchemy import SQLAlchemy
# from flask_login import login_user, current_user, logout_user, login_required
from app import db
# from app.users.forms import RegistrationForm,LoginForm,Account,ChangeEmail,Confirm_email,ResetPassword
from app.models import *
# from app.users.utils import send_mail,save_picture
# from random import randint
# from datetime import datetime
# from app.users.utils import *
from sqlalchemy import text,desc,func

question = Blueprint('question', __name__)  

@question.route("/comment", methods=["GET", "POST"])
def comment():
    if "user" in session:
        if request.method == "POST":
            comm = request.form.get("comment")
            sno = request.form.get("sno")
            comment_answer = Answers.query.filter_by(ans_no=sno).first()
            
            if comm:
        
                comment = Comments(sno=sno,
                                   comment=comm,
                                   username=session["user"],
                                   date=datetime.strftime(datetime.now(),"%d-%m-%y"),comment_user=Detail.query.filter_by(username=session["user"]).first(),comment_owner=comment_answer)
            else:
                comm = request.form.get("ques_comm")
                comment = Comments(ques_sno=sno,
                                   comment=comm,
                                   username=session["user"],
                                   date=datetime.strftime(datetime.now(),"%d-%m-%y"),comment_user=Detail.query.filter_by(username=session["user"]).first())
            answer = Question.query.filter_by(sno=sno).first()
            db.session.add(comment)
            db.session.commit()
            flash("Comment added", "success")
            if request.form.get("comment"):
                
                answer = Answers.query.filter_by(ans_no=sno).first()
                return redirect(
                    url_for("main.ques_page",
                            sno=answer.ques_id,
                            slug='-'.join(answer.owner.title[0:40].split(' '))) +
                    f"#a{answer.ans_no}")
            return redirect(
                url_for("main.ques_page",
                        sno=sno,
                        slug='-'.join(answer.title[0:40].split(' '))))
    else:
        flash("Sign in to comment", "warning")
        return redirect(url_for("users.signin"))


@question.route("/ques/<string:sno>", methods=["GET", "POST"])
def Ques(sno):
    if "user" in session and session["loggedin"] == True:
        question = Question.query.filter_by(sno=sno).first()
        if request.method == "POST":
            questitle = request.form.get("questitle")
            quesbody = request.form.get("quesbody")
            tag = request.form.get("questag")
            questag = tag.ljust(len(tag)+1," ").rjust(len(tag)+2," ") 
            
            if sno == "0":
                ques = Question(title=questitle,
                                body=quesbody,
                                tag=questag,
                                username=session["user"],
                                date=datetime.strftime(datetime.now(),"%d-%m-%y"), question_user=Detail.query.filter_by(username=session["user"]).first())
                db.session.add(ques)
                db.session.commit()

                flash("Question Posted successfully", "success")
            else:
                ques = Question.query.filter_by(sno=sno).first()
                ques.title = questitle
                ques.body = quesbody
                ques.tag = questag
                ques.question_user = Detail.query.filter_by(username=session["user"]).first()
                db.session.commit()
                flash("Question Edited successfully", "success")
            return redirect(
                url_for("main.ques_page",
                        sno=ques.sno,
                        slug='-'.join(ques.title[0:40].split(' '))))
        return render_template("question.html",
                               sno=sno,
                               question=question,
                               username=session["user"])
    else:
        return redirect("/signin")


@question.route('/delete', methods=["GET", "POST"])
def delete():
    if "user" in session and session["loggedin"] == True:
        if session["user"] == request.form.get("userDelete") or session[
                "user"] == request.args.get("userDelete"):
            if request.method == "POST":
                sno = request.form.get("delete")
                ques = Question.query.filter_by(sno=sno).first()

                slug = request.form.get("slug")
                flash("Question deleted successfully", "success")
                db.session.query(Vote).filter_by(no=sno,aq_vote="ques").delete()
                db.session.query(Comments).filter_by(ques_sno=sno).delete()
                db.session.delete(ques)
                db.session.commit()
                return redirect(url_for("home.index"))

            else:
                if request.args.get("ans_sno"):
                    sno = request.args.get("ans_sno")
                    a = sno
                    ques = Answers.query.filter_by(ans_no=sno).first()
                    flash("Answer deleted successfully", "success")
                    db.session.query(Comments).filter_by(sno=sno).delete()
                else:
                    sno = request.args.get("delete")
                    ques = Comments.query.filter_by(comm_sno=sno).first()
                    a = ques.sno
                    flash("comment deleted successfully", "success")
                slug = request.args.get("slug")
            slug = slug.split(",!2")
            print(slug)

            db.session.delete(ques)
            db.session.commit()
            return redirect(
                url_for("main.ques_page",
                        sno=slug[1],
                        slug='-'.join(slug[0][0:40].split(' '))) + f"#a{a}")
        else:
            return redirect("/")
    else:
        return redirect("/signin")

app/users/routes.py
from flask import (
    Blueprint,
    render_template,
    session,
    request,
    redirect,
    flash,
    abort
)
from app import db
from app.models import *
from app.users.utils import *
from sqlalchemy import func

users = Blueprint('users', __name__)


# profile page of a person.
@users.route("/profile/<string:name>")
def profile(name):
    user = Detail.query.filter_by(username=name).first()
    return render_template("profile.html",
                           user=user)


# page to edit profile details.
@users.route("/profile/edit/<string:name>", methods=["POST", "GET"])
def edit_profile(name):

    if "user" in session:
        if session["user"] == name:
            user = Detail.query.filter_by(username=session["user"]).first()
            if request.method == "POST":
                user.title = request.form["title"]
                user.about = request.form["about"]
                user.website_link = request.form["website"]
                user.twitter = request.form["twitter"]
                user.linkedin = request.form["linkedin"]
                user.github_username = request.form["github"]
                # taking the image
                try:
                    user.pic = upload_images(request.files["pic"])
                except:
                    pass
                db.session.commit()
            return render_template("profile_edit.html", user=user)

        abort(404)
    abort(404)


# signup system
@users.route('/signup', methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        name = request.form.get("username")
        email = request.form.get("email")
        password = request.form.get("password")
        cpassword = request.form.get("cpassword")
        contact = db.session.query(Detail).filter(func.lower(
            Detail.username) == name.lower()).first()
        if password == cpassword and contact is None:
            entry = Detail(username=name,
                           email=email,
                           password=password,
                           date=datetime.strftime(datetime.now(), "%d-%m-%y"))
            db.session.add(entry)
            db.session.commit()
            return redirect("/signin")
        elif contact is not None:
            flash("Username already taken ", "danger")
        elif password != cpassword:
            flash("Confirmation passwords does not match", "danger")
        else:
            flash("Sorry , we couldn't create your account. Please try again", "danger")
    return render_template("signup.html")


# signin system
@users.route('/signin', methods=["GET", "POST"])
def signin():
    if "user" in session and session["loggedin"] is True:
        return redirect("/")

    elif request.method == "POST":

        username = request.form.get("username").lower()
        password = request.form.get("password")
        contact = db.session.query(Detail).filter(func.lower(
            Detail.username) == username).first()

        if contact:

            if username == contact.username.lower() and \
                    password == contact.password:

                session["user"] = contact.username

                session["loggedin"] = True
                return redirect("/")

            else:
                flash("your password is incorrect", "danger")
                return render_template("signin.html")

        else:
            flash(f"No user exist of name {username}.\
                 Please sign up to continue", "danger")
            return render_template("signin.html")
    else:
        return render_template("signin.html")


@users.route('/logout', methods=["GET", "POST"])
def logout():
    session.clear()
    return redirect("/signin")

app/templates/about.html
{% extends "layout.html" %}

{% block headcss %}
<link rel="stylesheet" href='{{url_for("static",filename="css/about.css")}}'> 
{% endblock %}

{% block body %} 


<div class="container mt-3"> 
  <h3 class="text-center heading">The devs behind all of this work</h3>
	<div class="row">
	{% for i in users %}
		<div class="col" style="margin-bottom: 20px;">
            <div class="card cards text-center" style="align-items:center; padding:20px;">
                <img class="card-img-top" src="{{i.pic|get_img}}" alt="Card image cap" style="width:260px; height:260px; border-radius: 35px;">
    <div class="card-body">
      <h5 class="card-title">{{i.username}}</h5>
        <p class="card-text">
            {{i.title}}
        </p>
    </div>
    <a href="/profile/{{i.username}}" class="btn btn-primary">See Profile</a>
    </div>
    </div>
  {% endfor %}
    </div>
</div>

{% endblock %}


app/templates/edit_answer.html
{% extends "layout.html" %}
{% block body %} 

<script>
    if (window.location.pathname.endsWith("/0/") ){
        if ("{{username|safe}}" == "{{answer.username|safe}}"){
            console.log("hi")
        }
        else{
            console.log("bye")
            window.location.replace("/")
        }
    }
</script>

<form action="/edit_answer/{{sno}}" method="post">
    <div class="form-group" style="padding:0px 70px;">

        <label for="exampleFormControlTextarea1">Your Answer</label>
        <input type="hidden" name="username" value="{{answer.username}}" class="A_B_C_D">
        <textarea name="answer" class="form-control" id="mytextarea"
            rows="6"
            style="margin:10px; border-radius:10px;">{{answer.answer}}</textarea>
        <button type="submit" class="btn btn-primary" style="margin: 10px;">Post Answer</button>
    </div>

</form>
{% endblock %}

app/templates/flash.html
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for cat,message in messages %}
<div class="alert alert-{{cat}} alert-dismissible fade show" role="alert">
  {{message}}
  <button type="button" class="btn-close" data-mdb-dismiss="alert" aria-label="Close"></button>
</div>

{% endfor %}
{% endif %}
{% endwith %}

app/templates/profile_edit.html
{% extends "layout.html" %} {% block headcss %}
    <style>
        .body a {
            color: black;
            text-decoration: none;
        }

        .body a:hover {
            color: rgb(85, 85, 85);
        }

        .abt-below {
            height: 12rem;
            box-shadow: 3px 5px 14px rgb(0 0 0 / 15%);
            overflow-y: scroll;
        }

        .abt {
            overflow-y: scroll;
            height: 17rem;
            box-shadow: 3px 5px 14px rgb(0 0 0 / 15%);
        }

        .profile {
            color: black;
        }

        @media screen and (max-width: 767px) {
            .profile {
                height: 28rem;
            }
        }

        @media screen and (max-width: 576px) {
            .profile {
                height: 32rem;
            }
        }

        .link1 {
            padding-right: 2px !important;
            margin: 0px !important;
        }

        .link2 {
            padding-left: 2px !important;
            margin: 0px !important;
        }

        .side-link {
            display: inline;
        }

        .dropdown a:hover {
            color: rgba(14, 14, 14, 0.74);
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container-fluid mt-2">
        <form action="{{url_for('users.edit_profile', name=session['user'])}}" method="post" enctype="multipart/form-data">
            <div class="row body">
                <!--sidebar -->
                <div class="col-sm-2 d-md-block d-none">
                    <div class="row mt-3 g-2 ms-5">
                        <div class="col-12 mb-3">
                            <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Fpopular-services-brands-vol-2%2F512%2Fstackoverflow-512.png&f=1&nofb=1"
                                alt="logo" height="60" width="60">
                        </div>
                        <div class="col-12">
                            <a href="/profile/{{session['user']}}">My profile</a>
                        </div>
                        <div class="col-12">
                            <a href="/profile/edit/{{session['user']}}">Edit profile</a>
                        </div>
                        <div class="col-12">
                            <a href="#">Support</a>
                        </div>
                    </div>
                </div>
                <!-- main content -->
                <div class="col-md-10">
                    <div class="row">
                        <div class="col">
                            <!-- top bar -->
                            <div class="row align-items-center">
                                <div class="col">
                                    <h2>Edit profile</h2>
                                    <h6>Edit your profile info</h6>
                                </div>
                                <div class="col text-end">
                                    <div class="dropdown">
                                        <a class=" dropdown-toggle" href="#" id="dropdownMenuLink"
                                            data-mdb-toggle="dropdown" aria-expanded="false">
                                            Hello {{user.username}}
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                            <li><a class="dropdown-item" href="#">Change Email</a></li>
                                            <li><a class="dropdown-item" href="#">Change Password</a></li>
                                            <div class="d-md-none">
                                                <li><a class="dropdown-item" href="#">My profile</a></li>
                                                <li><a class="dropdown-item" href="#">Edit profile</a></li>
                                                <li><a class="dropdown-item" href="#">Contact</a></li>
                                            </div>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li><a class="dropdown-item" href="/logout">Logout</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- profile photo and links -->
                        <div class="mt-3 row row-cols-md-1 text-dark">
                            <div class="col-12 profile shadow col-md-5 text-center mb-md-0 mb-2">
                                <img height=145px width=145px
                                    src="{{user.pic|get_img}}"
                                    class="border-dark border border-2" id="myImg">
                                <div class="col">
                                    <label for="image_upload">
                                        <button type="button" class="mt-2 mb-4 btn-primary btn btn-rounded">Change picture</button>
                                    </label>
                                    <input type="file" name="pic" id="image_upload" style="display: none;" />
                                </div>
                                
                                <div class="row row-cols-md-1 g-3">
                                    <div class="col form-outline">
                                        <input class="form-control"
                                            value="{{user.username}}" id="name" required></input>
                                        <label class="form-label" for="name">Name</label>
                                    </div>
                                    <div class="col form-outline">
                                        <input class="form-control" name="title" id="title" value="{{user.title}}"></input>
                                        <label class="form-label" for="title">Title</label>
                                    </div>
                                </div>
                                <!-- social media links -->
                                <div class="row row-cols-1 row-cols-sm-2 g-2 mt-2">
                                    <div class="col">
                                        <div class="input-group mb-3">
                                            <span class="input-group-text" id="basic-addon1"><i
                                                    class="fab fa-github"></i></span>
                                            <input type="text" class="form-control" name="github" placeholder="Github Username"
                                                aria-label="Username" aria-describedby="basic-addon1" value="{{user.github_username}}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="input-group mb-3">
                                            <span class="input-group-text" id="basic-addon1"><i
                                                    class="fab fa-linkedin-in"></i></span>
                                            <input type="text" class="form-control" name="linkedin" placeholder="LinkedIn Username"
                                                aria-label="Username" aria-describedby="basic-addon1" value="{{user.linkedin}}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="input-group mb-3">
                                            <span class="input-group-text" id="basic-addon1"><i
                                                    class="fab fa-twitter"></i></span>
                                            <input type="text" class="form-control" name="twitter" placeholder="Twitter Username"
                                                aria-label="Username" aria-describedby="basic-addon1" value="{{user.twitter}}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="input-group mb-3">
                                            <span class="input-group-text" id="basic-addon1"><i
                                                    class="fas fa-globe"></i></span>
                                            <input type="url" name="website" class="form-control" placeholder="Website url"
                                                aria-label="website url" aria-describedby="basic-addon1" value="{{user.website_link}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-7">
                                <div class="row ms-md-1 my-sm-0">
                                    <!--about-->
                                    <div class="col-12 text-dark abt mb-3 rounded py-2">
                                        <h2>About</h2>
                                        <textarea style="width:100%;height: 60%;resize: none;"
                                            class="form-control" name="about">{{user.about}}</textarea>
                                            <button type="submit" class="btn mt-3 btn-primary btn-rounded">Submit</button>
                                    </div>
                                    <!-- lang and education -->
                                    <div class="col-12 abt-below text-dark py-3 px-3">
                                        <h2>Other info</h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <script>
        window.addEventListener('load', function () {
            document.querySelector('input[type="file"]').addEventListener('change', function () {
                if (this.files && this.files[0]) {
                    var img = document.getElementById('myImg');
                    img.onload = () => {
                        URL.revokeObjectURL(img.src);
                    }

                    img.src = URL.createObjectURL(this.files[0]);
                }
            });
        });
    </script>
{% endblock %}